# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79239f951610fa45ab1160d2fe4438f6"
name = "cloverkit-ugme"
application_url = "https://localhost:3458"
embedded = true

[access_scopes]
scopes = ""

[webhooks]
api_version = "2026-10"

[auth]
redirect_urls = [ "https://localhost:3458/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
